<?php
/**
 * @package    Joomla.Component.Builder
 *
 * @created    4th September, 2022
 * @author     Llewellyn van der Merwe <https://dev.vdm.io>
 * @git        Joomla Component Builder <https://git.vdm.dev/joomla/Component-Builder>
 * @copyright  Copyright (C) 2015 Vast Development Method. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace TrueChristianBible\Joomla\GetBible;


use TrueChristianBible\Joomla\Interfaces\TableInterface;
use TrueChristianBible\Joomla\Abstraction\BaseTable;


/**
 * Getbible Table Definition Class.
 * 
 * This class provides a centralized definition of all database-backed
 * areas, views, and their fields for Getbible.
 * 
 * It maps component entities to their schema definitions, field metadata,
 * storage behaviour, and relationships, enabling consistent code generation
 * and runtime operations across models, forms, and SQL migrations.
 * 
 * @since 3.2.0
 */
class Table extends BaseTable implements TableInterface
{
	/**
	 * Table Schema and Field Metadata Map.
	 *
	 * A fully structured, associative array containing definitions for
	 * every database table (area/view) used by the component. Each table
	 * contains its field definitions with the following details:
	 *
	 * - **name**: The column/field name in the database.
	 * - **label**: The Joomla language constant for field display text.
	 * - **type**: The form field type (text, textarea, editor, radio, list, etc.).
	 * - **title**: Whether this field is the primary title field for the view.
	 * - **list**: The list view this field belongs to.
	 * - **store**: Any special storage encoding (e.g. `base64`, `json`, `basic_encryption`).
	 * - **tab_name**: The logical tab grouping for form display.
	 * - **db**: An array describing the database column definition:
	 *   - `type`: The SQL column type (e.g. VARCHAR(255), INT(11)).
	 *   - `default`: Default value or `EMPTY`.
	 *   - `GUID`: A unique identifier.
	 *   - `null_switch`: Whether NULL is allowed (`NULL` or `NOT NULL`).
	 *   - `unique_key`: Boolean indicating if a unique key is enforced.
	 *   - `key`: Boolean indicating if it is indexed.
	 * - **link**: If applicable, describes a foreign key relationship
	 *   (target table, component, entity, value field, and key field).
	 * - **fields**: (Optional) Subfield definitions for subforms.
	 *
	 * This array is the canonical reference used by developers to dynamically
	 * build database migrations, generate forms, create models, and ensure
	 * consistent schema management across installations and updates.
	 *
	 * @var   array
	 * @since 3.2.0
	 */
	protected array $tables = [
		'linker' => [
			'name' => [
				'name' => 'name',
				'guid' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
				'label' => 'COM_GETBIBLE_LINKER_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'linkers',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_GETBIBLE_LINKER_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'linkers',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'public_tagged_verses' => [
				'name' => 'public_tagged_verses',
				'guid' => '78abc255-ee4b-432b-86e9-c793b2ed45ad',
				'label' => 'COM_GETBIBLE_LINKER_PUBLIC_TAGGED_VERSES_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'linkers',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '78abc255-ee4b-432b-86e9-c793b2ed45ad',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'public_notes' => [
				'name' => 'public_notes',
				'guid' => '1cbd3fa9-431e-43d5-b3ad-375e7c798b95',
				'label' => 'COM_GETBIBLE_LINKER_PUBLIC_NOTES_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'linkers',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '1cbd3fa9-431e-43d5-b3ad-375e7c798b95',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'note' => [
			'book_nr' => [
				'name' => 'book_nr',
				'guid' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
				'label' => 'COM_GETBIBLE_NOTE_BOOK_NR_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'linker' => [
				'name' => 'linker',
				'guid' => '7b2429da-a049-4262-b39a-9d07ba2bf97f',
				'label' => 'COM_GETBIBLE_NOTE_LINKER_LABEL',
				'type' => 'linkers',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '7b2429da-a049-4262-b39a-9d07ba2bf97f',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_linker',
					'component' => 'com_getbible',
					'entity' => 'linker',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'access' => [
				'name' => 'access',
				'guid' => '57f36767-b576-4159-9b53-15228e6f9702',
				'label' => 'COM_GETBIBLE_NOTE_ACCESS_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '57f36767-b576-4159-9b53-15228e6f9702',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_GETBIBLE_NOTE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'note' => [
				'name' => 'note',
				'guid' => '995f6d4a-4a97-4744-ac5b-d66e6e4f74c5',
				'label' => 'COM_GETBIBLE_NOTE_NOTE_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '995f6d4a-4a97-4744-ac5b-d66e6e4f74c5',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'verse' => [
				'name' => 'verse',
				'guid' => 'c5e07e4f-14e2-4ff8-b956-0077b77c4668',
				'label' => 'COM_GETBIBLE_NOTE_VERSE_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'c5e07e4f-14e2-4ff8-b956-0077b77c4668',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'chapter' => [
				'name' => 'chapter',
				'guid' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
				'label' => 'COM_GETBIBLE_NOTE_CHAPTER_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'notes',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
		],
		'tagged_verse' => [
			'book_nr' => [
				'name' => 'book_nr',
				'guid' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_BOOK_NR_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_ABBREVIATION_LABEL',
				'type' => 'translations',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_translation',
					'component' => 'com_getbible',
					'entity' => 'translation',
					'value' => 'translation',
					'key' => 'abbreviation',
				],
			],
			'access' => [
				'name' => 'access',
				'guid' => '57f36767-b576-4159-9b53-15228e6f9702',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_ACCESS_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '57f36767-b576-4159-9b53-15228e6f9702',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'linker' => [
				'name' => 'linker',
				'guid' => '7b2429da-a049-4262-b39a-9d07ba2bf97f',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_LINKER_LABEL',
				'type' => 'linkers',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '7b2429da-a049-4262-b39a-9d07ba2bf97f',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_linker',
					'component' => 'com_getbible',
					'entity' => 'linker',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'tag' => [
				'name' => 'tag',
				'guid' => '338d1659-8875-46a9-a342-e214f6485166',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_TAG_LABEL',
				'type' => 'tagers',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '338d1659-8875-46a9-a342-e214f6485166',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_tag',
					'component' => 'com_getbible',
					'entity' => 'tag',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'verse' => [
				'name' => 'verse',
				'guid' => 'c5e07e4f-14e2-4ff8-b956-0077b77c4668',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_VERSE_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'c5e07e4f-14e2-4ff8-b956-0077b77c4668',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'chapter' => [
				'name' => 'chapter',
				'guid' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
				'label' => 'COM_GETBIBLE_TAGGED_VERSE_CHAPTER_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'tagged_verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
		],
		'prompt' => [
			'name' => [
				'name' => 'name',
				'guid' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
				'label' => 'COM_GETBIBLE_PROMPT_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'integration' => [
				'name' => 'integration',
				'guid' => 'cc4a4d1b-b660-4473-9728-2aca5d78b43f',
				'label' => 'COM_GETBIBLE_PROMPT_INTEGRATION_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '1',
					'GUID' => 'cc4a4d1b-b660-4473-9728-2aca5d78b43f',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'cache_behaviour' => [
				'name' => 'cache_behaviour',
				'guid' => 'a8ef8e48-fedd-44dc-b4c7-306247bab687',
				'label' => 'COM_GETBIBLE_PROMPT_CACHE_BEHAVIOUR_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => 'a8ef8e48-fedd-44dc-b4c7-306247bab687',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => '6cf39fcf-7d48-418b-8acc-56255ed702d6',
				'label' => 'COM_GETBIBLE_PROMPT_ABBREVIATION_LABEL',
				'type' => 'targettranslations',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => 'EMPTY',
					'GUID' => '6cf39fcf-7d48-418b-8acc-56255ed702d6',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_translation',
					'component' => 'com_getbible',
					'entity' => 'translation',
					'value' => 'translation',
					'key' => 'abbreviation',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_GETBIBLE_PROMPT_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'model' => [
				'name' => 'model',
				'guid' => 'f9447157-7322-49c2-90f0-2c548f20e27d',
				'label' => 'COM_GETBIBLE_PROMPT_MODEL_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'VARCHAR(50)',
					'default' => '',
					'GUID' => 'f9447157-7322-49c2-90f0-2c548f20e27d',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'presence_penalty' => [
				'name' => 'presence_penalty',
				'guid' => '19e2b4ba-0a4a-4ead-89f6-c5e1339b686a',
				'label' => 'COM_GETBIBLE_PROMPT_PRESENCE_PENALTY_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '19e2b4ba-0a4a-4ead-89f6-c5e1339b686a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'org_token' => [
				'name' => 'org_token',
				'guid' => 'a63a22f8-f9e0-43b4-ad11-7de15837cc0b',
				'label' => 'COM_GETBIBLE_PROMPT_ORG_TOKEN_LABEL',
				'type' => 'password',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => 'a63a22f8-f9e0-43b4-ad11-7de15837cc0b',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'token' => [
				'name' => 'token',
				'guid' => 'cf514cb4-4e31-41a9-ba34-e676f06edffe',
				'label' => 'COM_GETBIBLE_PROMPT_TOKEN_LABEL',
				'type' => 'password',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => 'cf514cb4-4e31-41a9-ba34-e676f06edffe',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'n_override' => [
				'name' => 'n_override',
				'guid' => 'c9252c5a-d367-4656-b649-f0937503145c',
				'label' => 'COM_GETBIBLE_PROMPT_N_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => 'c9252c5a-d367-4656-b649-f0937503145c',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'cache_capacity' => [
				'name' => 'cache_capacity',
				'guid' => 'ec5abb0b-061d-41be-8e0d-7833be523576',
				'label' => 'COM_GETBIBLE_PROMPT_CACHE_CAPACITY_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'ec5abb0b-061d-41be-8e0d-7833be523576',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'messages' => [
				'name' => 'messages',
				'guid' => 'd3e8b1c0-7052-4795-b5d3-08c7d0601d91',
				'label' => 'COM_GETBIBLE_PROMPT_MESSAGES_LABEL',
				'type' => 'subform',
				'title' => false,
				'list' => 'prompts',
				'store' => 'json',
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => 'd3e8b1c0-7052-4795-b5d3-08c7d0601d91',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
				'fields' => [
					'role' => [
						'name' => 'role',
						'type' => 'list',
						'link' => NULL,
					],
					'content' => [
						'name' => 'content',
						'type' => 'textarea',
						'link' => NULL,
					],
					'name' => [
						'name' => 'name',
						'type' => 'text',
						'link' => NULL,
					],
				],
			],
			'response_retrieval' => [
				'name' => 'response_retrieval',
				'guid' => '69928772-73c3-4e45-b121-3b373472e3b6',
				'label' => 'COM_GETBIBLE_PROMPT_RESPONSE_RETRIEVAL_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '69928772-73c3-4e45-b121-3b373472e3b6',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'frequency_penalty_override' => [
				'name' => 'frequency_penalty_override',
				'guid' => '4d7afc99-c3ee-446b-98b0-73d525695b6e',
				'label' => 'COM_GETBIBLE_PROMPT_FREQUENCY_PENALTY_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '4d7afc99-c3ee-446b-98b0-73d525695b6e',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'n' => [
				'name' => 'n',
				'guid' => 'cd79e71a-2258-4c6d-b9d0-d78917d1f5ab',
				'label' => 'COM_GETBIBLE_PROMPT_N_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'cd79e71a-2258-4c6d-b9d0-d78917d1f5ab',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'max_tokens_override' => [
				'name' => 'max_tokens_override',
				'guid' => '5f2e8efa-f74c-4457-9214-cac366265e1a',
				'label' => 'COM_GETBIBLE_PROMPT_MAX_TOKENS_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '5f2e8efa-f74c-4457-9214-cac366265e1a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'token_override' => [
				'name' => 'token_override',
				'guid' => '070ea511-e70d-4460-90b3-bc880efb23e2',
				'label' => 'COM_GETBIBLE_PROMPT_TOKEN_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '070ea511-e70d-4460-90b3-bc880efb23e2',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'max_tokens' => [
				'name' => 'max_tokens',
				'guid' => '20cd21e3-3cb9-4969-a631-a8e247829519',
				'label' => 'COM_GETBIBLE_PROMPT_MAX_TOKENS_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '20cd21e3-3cb9-4969-a631-a8e247829519',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'ai_org_token_override' => [
				'name' => 'ai_org_token_override',
				'guid' => '495ea19a-7e80-4464-a25c-e6bdf8430c1e',
				'label' => 'COM_GETBIBLE_PROMPT_AI_ORG_TOKEN_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '495ea19a-7e80-4464-a25c-e6bdf8430c1e',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'temperature_override' => [
				'name' => 'temperature_override',
				'guid' => '40687b85-e2a9-4432-ba9b-e9a64bf643e8',
				'label' => 'COM_GETBIBLE_PROMPT_TEMPERATURE_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '40687b85-e2a9-4432-ba9b-e9a64bf643e8',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'presence_penalty_override' => [
				'name' => 'presence_penalty_override',
				'guid' => '8bde9292-ec91-4c3f-ae11-24997997cbb1',
				'label' => 'COM_GETBIBLE_PROMPT_PRESENCE_PENALTY_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '8bde9292-ec91-4c3f-ae11-24997997cbb1',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'top_p_override' => [
				'name' => 'top_p_override',
				'guid' => '9524dbb5-1d23-437d-95a1-6dd05bf17461',
				'label' => 'COM_GETBIBLE_PROMPT_TOP_P_OVERRIDE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '9524dbb5-1d23-437d-95a1-6dd05bf17461',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'frequency_penalty' => [
				'name' => 'frequency_penalty',
				'guid' => '1d4138b6-7bfd-431f-a0bb-496518e44600',
				'label' => 'COM_GETBIBLE_PROMPT_FREQUENCY_PENALTY_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '1d4138b6-7bfd-431f-a0bb-496518e44600',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'top_p' => [
				'name' => 'top_p',
				'guid' => '86834ef2-49f2-4367-b1db-2e4dc66dd8f8',
				'label' => 'COM_GETBIBLE_PROMPT_TOP_P_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '86834ef2-49f2-4367-b1db-2e4dc66dd8f8',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'temperature' => [
				'name' => 'temperature',
				'guid' => '14855f78-fc97-4e67-9769-ea1bfb29477d',
				'label' => 'COM_GETBIBLE_PROMPT_TEMPERATURE_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'prompts',
				'store' => NULL,
				'tab_name' => 'Open AI',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '14855f78-fc97-4e67-9769-ea1bfb29477d',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'open_ai_response' => [
			'response_id' => [
				'name' => 'response_id',
				'guid' => 'd8429674-cbbb-4810-ab11-e0f35733e741',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_RESPONSE_ID_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => 'd8429674-cbbb-4810-ab11-e0f35733e741',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'prompt' => [
				'name' => 'prompt',
				'guid' => '80260582-7454-4ff5-92c2-53a2964e458a',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_PROMPT_LABEL',
				'type' => 'prompts',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => 'EMPTY',
					'GUID' => '80260582-7454-4ff5-92c2-53a2964e458a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_prompt',
					'component' => 'com_getbible',
					'entity' => 'prompt',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'response_object' => [
				'name' => 'response_object',
				'guid' => '326c6b2c-4c6b-4582-af1f-2735619f0b14',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_RESPONSE_OBJECT_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => '326c6b2c-4c6b-4582-af1f-2735619f0b14',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'response_model' => [
				'name' => 'response_model',
				'guid' => 'e75ca941-207c-4114-885e-8bb2e3f84cff',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_RESPONSE_MODEL_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => 'e75ca941-207c-4114-885e-8bb2e3f84cff',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'total_tokens' => [
				'name' => 'total_tokens',
				'guid' => '7cbad073-7b58-4df2-9344-975f1eac7d49',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_TOTAL_TOKENS_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '7cbad073-7b58-4df2-9344-975f1eac7d49',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'n' => [
				'name' => 'n',
				'guid' => 'e79af807-e311-41c7-a659-322fc2730a05',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_N_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'e79af807-e311-41c7-a659-322fc2730a05',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'frequency_penalty' => [
				'name' => 'frequency_penalty',
				'guid' => '712a35be-6b65-4065-b631-4321b4ccb4f2',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_FREQUENCY_PENALTY_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '712a35be-6b65-4065-b631-4321b4ccb4f2',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'presence_penalty' => [
				'name' => 'presence_penalty',
				'guid' => '8e8aae71-cf35-4cca-87a1-5786ec5f0b63',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_PRESENCE_PENALTY_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '8e8aae71-cf35-4cca-87a1-5786ec5f0b63',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'word' => [
				'name' => 'word',
				'guid' => 'accb2d93-6827-4ae6-894f-b5bfa0fbcf2c',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_WORD_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => 'accb2d93-6827-4ae6-894f-b5bfa0fbcf2c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'chapter' => [
				'name' => 'chapter',
				'guid' => 'b5911bd1-8aaf-4254-bb4c-40fe69bc1ec9',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_CHAPTER_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'b5911bd1-8aaf-4254-bb4c-40fe69bc1ec9',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'lcsh' => [
				'name' => 'lcsh',
				'guid' => '1a873719-2e33-4534-ac6c-0090cce5e28e',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_LCSH_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => '1a873719-2e33-4534-ac6c-0090cce5e28e',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'completion_tokens' => [
				'name' => 'completion_tokens',
				'guid' => 'cc33d028-3381-458c-adfe-dd18283d168f',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_COMPLETION_TOKENS_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'cc33d028-3381-458c-adfe-dd18283d168f',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'prompt_tokens' => [
				'name' => 'prompt_tokens',
				'guid' => '45196d6b-d9d4-4f0b-beef-d61ebc591ef2',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_PROMPT_TOKENS_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '45196d6b-d9d4-4f0b-beef-d61ebc591ef2',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'response_created' => [
				'name' => 'response_created',
				'guid' => '4b26801d-82b4-4659-b6a7-cd37c989ebc7',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_RESPONSE_CREATED_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => '4b26801d-82b4-4659-b6a7-cd37c989ebc7',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => '6cf39fcf-7d48-418b-8acc-56255ed702d6',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_ABBREVIATION_LABEL',
				'type' => 'targettranslations',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => 'EMPTY',
					'GUID' => '6cf39fcf-7d48-418b-8acc-56255ed702d6',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_translation',
					'component' => 'com_getbible',
					'entity' => 'translation',
					'value' => 'translation',
					'key' => 'abbreviation',
				],
			],
			'language' => [
				'name' => 'language',
				'guid' => '6c3e4d53-7513-4172-bdc9-c236b9919b04',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_LANGUAGE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => '6c3e4d53-7513-4172-bdc9-c236b9919b04',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'max_tokens' => [
				'name' => 'max_tokens',
				'guid' => 'd2e6bb32-9f77-430c-ac75-f03722741c5a',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_MAX_TOKENS_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'd2e6bb32-9f77-430c-ac75-f03722741c5a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'book' => [
				'name' => 'book',
				'guid' => '45c16e7f-a3c6-4136-b987-4f51bba7c5ec',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_BOOK_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '45c16e7f-a3c6-4136-b987-4f51bba7c5ec',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'temperature' => [
				'name' => 'temperature',
				'guid' => 'd3b490fd-4446-4cde-bbf1-2991197db434',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_TEMPERATURE_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => 'd3b490fd-4446-4cde-bbf1-2991197db434',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'verse' => [
				'name' => 'verse',
				'guid' => '7e4a4982-b2ee-4017-9ad2-eea5c0ed8e4c',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_VERSE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => 'EMPTY',
					'GUID' => '7e4a4982-b2ee-4017-9ad2-eea5c0ed8e4c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'top_p' => [
				'name' => 'top_p',
				'guid' => '2abbeba5-6088-41aa-89e8-4272ca032522',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_TOP_P_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'FLOAT(11)',
					'default' => '0',
					'GUID' => '2abbeba5-6088-41aa-89e8-4272ca032522',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'selected_word' => [
				'name' => 'selected_word',
				'guid' => '3414e6ea-3373-4013-a5ed-2b442afe7733',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_SELECTED_WORD_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Bible',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '3414e6ea-3373-4013-a5ed-2b442afe7733',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'model' => [
				'name' => 'model',
				'guid' => '8387d715-3d45-4a09-b2f1-35166225cf27',
				'label' => 'COM_GETBIBLE_OPEN_AI_RESPONSE_MODEL_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'open_ai_responses',
				'store' => NULL,
				'tab_name' => 'Prompt',
				'db' => [
					'type' => 'VARCHAR(50)',
					'default' => '',
					'GUID' => '8387d715-3d45-4a09-b2f1-35166225cf27',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'open_ai_message' => [
			'role' => [
				'name' => 'role',
				'guid' => '0aaae2d4-4570-430f-9830-6162fb91f689',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_ROLE_LABEL',
				'type' => 'list',
				'title' => true,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '0aaae2d4-4570-430f-9830-6162fb91f689',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'open_ai_response' => [
				'name' => 'open_ai_response',
				'guid' => '07de38fc-c205-4b13-a5a0-4044440fd53a',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_OPEN_AI_RESPONSE_LABEL',
				'type' => 'openairesponses',
				'title' => false,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '07de38fc-c205-4b13-a5a0-4044440fd53a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_open_ai_response',
					'component' => 'com_getbible',
					'entity' => 'open_ai_response',
					'value' => 'response_id',
					'key' => 'response_id',
				],
			],
			'prompt' => [
				'name' => 'prompt',
				'guid' => '80260582-7454-4ff5-92c2-53a2964e458a',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_PROMPT_LABEL',
				'type' => 'prompts',
				'title' => false,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => 'EMPTY',
					'GUID' => '80260582-7454-4ff5-92c2-53a2964e458a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_prompt',
					'component' => 'com_getbible',
					'entity' => 'prompt',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'source' => [
				'name' => 'source',
				'guid' => '930fb9fa-d1a8-4a08-a9b6-b8d2697bf40a',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_SOURCE_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '930fb9fa-d1a8-4a08-a9b6-b8d2697bf40a',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'content' => [
				'name' => 'content',
				'guid' => '43b42f9b-9586-46be-8e90-b144c3602797',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_CONTENT_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '43b42f9b-9586-46be-8e90-b144c3602797',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'name' => [
				'name' => 'name',
				'guid' => '51e05bdb-4ec8-46dd-804c-339624d7d652',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_NAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '51e05bdb-4ec8-46dd-804c-339624d7d652',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'index' => [
				'name' => 'index',
				'guid' => 'a7a9933a-97e2-46ca-a886-2eb5c104a4f2',
				'label' => 'COM_GETBIBLE_OPEN_AI_MESSAGE_INDEX_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'open_ai_messages',
				'store' => NULL,
				'tab_name' => 'Message',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'a7a9933a-97e2-46ca-a886-2eb5c104a4f2',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'password' => [
			'name' => [
				'name' => 'name',
				'guid' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
				'label' => 'COM_GETBIBLE_PASSWORD_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'passwords',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'linker' => [
				'name' => 'linker',
				'guid' => '9aa1ba9c-33df-40e6-99d7-646cfe16eec7',
				'label' => 'COM_GETBIBLE_PASSWORD_LINKER_LABEL',
				'type' => 'linkers',
				'title' => false,
				'list' => 'passwords',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '9aa1ba9c-33df-40e6-99d7-646cfe16eec7',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_linker',
					'component' => 'com_getbible',
					'entity' => 'linker',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_GETBIBLE_PASSWORD_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'passwords',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'password' => [
				'name' => 'password',
				'guid' => '3069ffb7-bcf7-45bd-b3eb-d5f7de4f80cf',
				'label' => 'COM_GETBIBLE_PASSWORD_PASSWORD_LABEL',
				'type' => 'password',
				'title' => false,
				'list' => 'passwords',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => '3069ffb7-bcf7-45bd-b3eb-d5f7de4f80cf',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'tag' => [
			'name' => [
				'name' => 'name',
				'guid' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
				'label' => 'COM_GETBIBLE_TAG_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'f318f3ef-eb0e-4ad8-9c81-f475c9618014',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'linker' => [
				'name' => 'linker',
				'guid' => '7b2429da-a049-4262-b39a-9d07ba2bf97f',
				'label' => 'COM_GETBIBLE_TAG_LINKER_LABEL',
				'type' => 'linkers',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '7b2429da-a049-4262-b39a-9d07ba2bf97f',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_linker',
					'component' => 'com_getbible',
					'entity' => 'linker',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'access' => [
				'name' => 'access',
				'guid' => '57f36767-b576-4159-9b53-15228e6f9702',
				'label' => 'COM_GETBIBLE_TAG_ACCESS_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '57f36767-b576-4159-9b53-15228e6f9702',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_GETBIBLE_TAG_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
				'label' => 'COM_GETBIBLE_TAG_DESCRIPTION_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
		],
		'translation' => [
			'translation' => [
				'name' => 'translation',
				'guid' => '72fa0198-4881-4bc3-b42b-e3e32ad47665',
				'label' => 'COM_GETBIBLE_TRANSLATION_TRANSLATION_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '72fa0198-4881-4bc3-b42b-e3e32ad47665',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => 'e997452e-239b-472e-9b15-adcc91664a36',
				'label' => 'COM_GETBIBLE_TRANSLATION_ABBREVIATION_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => 'e997452e-239b-472e-9b15-adcc91664a36',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'language' => [
				'name' => 'language',
				'guid' => '5a956d5e-5145-4fab-863b-b7a5d92e4fb9',
				'label' => 'COM_GETBIBLE_TRANSLATION_LANGUAGE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => '5a956d5e-5145-4fab-863b-b7a5d92e4fb9',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'direction' => [
				'name' => 'direction',
				'guid' => '2e6bd7af-443e-431b-b358-efbc079cf21c',
				'label' => 'COM_GETBIBLE_TRANSLATION_DIRECTION_LABEL',
				'type' => 'radio',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '2e6bd7af-443e-431b-b358-efbc079cf21c',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_history' => [
				'name' => 'distribution_history',
				'guid' => '4a68d3f0-7af5-49b3-83e7-36720dc27fce',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_HISTORY_LABEL',
				'type' => 'subform',
				'title' => false,
				'list' => 'translations',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '4a68d3f0-7af5-49b3-83e7-36720dc27fce',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
				'fields' => [
					'version' => [
						'name' => 'version',
						'type' => 'text',
						'link' => NULL,
					],
					'description' => [
						'name' => 'description',
						'type' => 'text',
						'link' => NULL,
					],
				],
			],
			'distribution_about' => [
				'name' => 'distribution_about',
				'guid' => '9b9b6e10-6c6f-4526-9437-002b129371e9',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_ABOUT_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '9b9b6e10-6c6f-4526-9437-002b129371e9',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_license' => [
				'name' => 'distribution_license',
				'guid' => 'c7eaee18-cc01-480c-a0b1-362b034fc5ad',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_LICENSE_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => 'c7eaee18-cc01-480c-a0b1-362b034fc5ad',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_source' => [
				'name' => 'distribution_source',
				'guid' => 'a7accfe7-7350-4856-a6dc-1d4bfc3e5bec',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_SOURCE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => 'a7accfe7-7350-4856-a6dc-1d4bfc3e5bec',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_sourcetype' => [
				'name' => 'distribution_sourcetype',
				'guid' => 'eaa07bd9-42b8-405a-8d98-09075b1df25a',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_SOURCETYPE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'eaa07bd9-42b8-405a-8d98-09075b1df25a',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_versification' => [
				'name' => 'distribution_versification',
				'guid' => '302bc57c-ba69-49af-b057-0df9366f5713',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_VERSIFICATION_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '302bc57c-ba69-49af-b057-0df9366f5713',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'sha' => [
				'name' => 'sha',
				'guid' => '9b25c783-09dd-49d5-aa2e-a6d6c8a1e86d',
				'label' => 'COM_GETBIBLE_TRANSLATION_SHA_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '9b25c783-09dd-49d5-aa2e-a6d6c8a1e86d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'encoding' => [
				'name' => 'encoding',
				'guid' => '9215a5e6-3a18-43c8-90e8-0e3e49e4947a',
				'label' => 'COM_GETBIBLE_TRANSLATION_ENCODING_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '9215a5e6-3a18-43c8-90e8-0e3e49e4947a',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_lcsh' => [
				'name' => 'distribution_lcsh',
				'guid' => 'dee30189-a5c1-4f6f-9c5b-42065a6e2c4a',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_LCSH_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => 'dee30189-a5c1-4f6f-9c5b-42065a6e2c4a',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_version_date' => [
				'name' => 'distribution_version_date',
				'guid' => '43553804-abc1-4691-ad57-c9d9a502d472',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_VERSION_DATE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '43553804-abc1-4691-ad57-c9d9a502d472',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_version' => [
				'name' => 'distribution_version',
				'guid' => '7ad19500-912f-4dd8-8746-dd2f625df9be',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_VERSION_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '7ad19500-912f-4dd8-8746-dd2f625df9be',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'lang' => [
				'name' => 'lang',
				'guid' => 'e8bf26e3-0777-4d2b-9b94-6abd39a55140',
				'label' => 'COM_GETBIBLE_TRANSLATION_LANG_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'e8bf26e3-0777-4d2b-9b94-6abd39a55140',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'distribution_abbreviation' => [
				'name' => 'distribution_abbreviation',
				'guid' => '96f9d04b-fd0a-4bc0-95e0-ea569d6acc39',
				'label' => 'COM_GETBIBLE_TRANSLATION_DISTRIBUTION_ABBREVIATION_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'translations',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '96f9d04b-fd0a-4bc0-95e0-ea569d6acc39',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'book' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_GETBIBLE_BOOK_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'books',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
				'label' => 'COM_GETBIBLE_BOOK_ABBREVIATION_LABEL',
				'type' => 'translations',
				'title' => false,
				'list' => 'books',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_translation',
					'component' => 'com_getbible',
					'entity' => 'translation',
					'value' => 'translation',
					'key' => 'abbreviation',
				],
			],
			'nr' => [
				'name' => 'nr',
				'guid' => '2b9ff925-44f7-4e15-9254-90b8ea74d318',
				'label' => 'COM_GETBIBLE_BOOK_NR_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'books',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => '2b9ff925-44f7-4e15-9254-90b8ea74d318',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'sha' => [
				'name' => 'sha',
				'guid' => '9b25c783-09dd-49d5-aa2e-a6d6c8a1e86d',
				'label' => 'COM_GETBIBLE_BOOK_SHA_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'books',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '9b25c783-09dd-49d5-aa2e-a6d6c8a1e86d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'chapter' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_GETBIBLE_CHAPTER_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'chapters',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'chapter' => [
				'name' => 'chapter',
				'guid' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
				'label' => 'COM_GETBIBLE_CHAPTER_CHAPTER_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'chapters',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'book_nr' => [
				'name' => 'book_nr',
				'guid' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
				'label' => 'COM_GETBIBLE_CHAPTER_BOOK_NR_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'chapters',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
				'label' => 'COM_GETBIBLE_CHAPTER_ABBREVIATION_LABEL',
				'type' => 'translations',
				'title' => false,
				'list' => 'chapters',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_translation',
					'component' => 'com_getbible',
					'entity' => 'translation',
					'value' => 'translation',
					'key' => 'abbreviation',
				],
			],
			'sha' => [
				'name' => 'sha',
				'guid' => '9b25c783-09dd-49d5-aa2e-a6d6c8a1e86d',
				'label' => 'COM_GETBIBLE_CHAPTER_SHA_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'chapters',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '9b25c783-09dd-49d5-aa2e-a6d6c8a1e86d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'verse' => [
			'book_nr' => [
				'name' => 'book_nr',
				'guid' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
				'label' => 'COM_GETBIBLE_VERSE_BOOK_NR_LABEL',
				'type' => 'number',
				'title' => true,
				'list' => 'verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'd48bc87e-adb2-4a64-a327-0cc6506d8617',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'chapter' => [
				'name' => 'chapter',
				'guid' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
				'label' => 'COM_GETBIBLE_VERSE_CHAPTER_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'e563aeb4-fb5d-40d3-b9f3-07066cca9ee0',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'verse' => [
				'name' => 'verse',
				'guid' => 'c5e07e4f-14e2-4ff8-b956-0077b77c4668',
				'label' => 'COM_GETBIBLE_VERSE_VERSE_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(7)',
					'default' => '0',
					'GUID' => 'c5e07e4f-14e2-4ff8-b956-0077b77c4668',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
				'label' => 'COM_GETBIBLE_VERSE_ABBREVIATION_LABEL',
				'type' => 'translations',
				'title' => false,
				'list' => 'verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(100)',
					'default' => '',
					'GUID' => '2bf9662b-b0d1-4db1-ab8f-f2d8197464ee',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__getbible_translation',
					'component' => 'com_getbible',
					'entity' => 'translation',
					'value' => 'translation',
					'key' => 'abbreviation',
				],
			],
			'text' => [
				'name' => 'text',
				'guid' => '1f4eb0e9-d4b5-4d3b-8c58-258b74303db1',
				'label' => 'COM_GETBIBLE_VERSE_TEXT_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '1f4eb0e9-d4b5-4d3b-8c58-258b74303db1',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_GETBIBLE_VERSE_NAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'verses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
	];
}

